"""initial schema

Revision ID: c65c30567800
Revises: 
Create Date: 2026-08-30 17:58:12.792247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c65c30567800'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ventures',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('one_liner', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('target_market', sa.Text(), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('draft', 'running', 'completed', 'failed', name='venturestatus', native_enum=False, length=20), server_default='draft', nullable=False),
    sa.Column('venture_score', sa.Float(), nullable=True),
    sa.Column('iteration_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('venture_score IS NULL OR (venture_score >= 0 AND venture_score <= 100)', name='ck_ventures_score_range'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ventures_created_at'), 'ventures', ['created_at'], unique=False)
    op.create_index(op.f('ix_ventures_status'), 'ventures', ['status'], unique=False)
    op.create_table('agent_runs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('venture_id', sa.String(length=32), nullable=False),
    sa.Column('agent_name', sa.Enum('planner', 'market_research', 'competitor', 'customer', 'financial_risk', 'executive_decision', 'report_generator', name='agentname', native_enum=False, length=50), nullable=False),
    sa.Column('iteration_number', sa.Integer(), server_default='1', nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'completed', 'failed', name='agentrunstatus', native_enum=False, length=20), server_default='pending', nullable=False),
    sa.Column('input_state', sa.JSON(), nullable=True),
    sa.Column('output_state', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['venture_id'], ['ventures.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_runs_venture_id'), 'agent_runs', ['venture_id'], unique=False)
    op.create_table('improvement_iterations',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('venture_id', sa.String(length=32), nullable=False),
    sa.Column('iteration_number', sa.Integer(), nullable=False),
    sa.Column('previous_score', sa.Float(), nullable=True),
    sa.Column('new_score', sa.Float(), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['venture_id'], ['ventures.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_improvement_iterations_venture_id'), 'improvement_iterations', ['venture_id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('venture_id', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('venture_score', sa.Float(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('sections', sa.JSON(), nullable=False),
    sa.Column('recommendations', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('venture_score >= 0 AND venture_score <= 100', name='ck_reports_score_range'),
    sa.ForeignKeyConstraint(['venture_id'], ['ventures.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('venture_id', 'version', name='ux_reports_venture_version')
    )
    op.create_index(op.f('ix_reports_venture_id'), 'reports', ['venture_id'], unique=False)
    op.create_table('research_findings',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('venture_id', sa.String(length=32), nullable=False),
    sa.Column('category', sa.Enum('market', 'competitor', 'customer', 'financial', 'marketing', 'risk', name='findingcategory', native_enum=False, length=20), nullable=False),
    sa.Column('source_type', sa.Enum('tavily', 'firecrawl', 'llm', name='findingsourcetype', native_enum=False, length=20), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['venture_id'], ['ventures.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_findings_category'), 'research_findings', ['category'], unique=False)
    op.create_index(op.f('ix_research_findings_venture_id'), 'research_findings', ['venture_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_research_findings_venture_id'), table_name='research_findings')
    op.drop_index(op.f('ix_research_findings_category'), table_name='research_findings')
    op.drop_table('research_findings')
    op.drop_index(op.f('ix_reports_venture_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_improvement_iterations_venture_id'), table_name='improvement_iterations')
    op.drop_table('improvement_iterations')
    op.drop_index(op.f('ix_agent_runs_venture_id'), table_name='agent_runs')
    op.drop_table('agent_runs')
    op.drop_index(op.f('ix_ventures_status'), table_name='ventures')
    op.drop_index(op.f('ix_ventures_created_at'), table_name='ventures')
    op.drop_table('ventures')
    # ### end Alembic commands ###
